version: '3.3'


services:
    hdfsnamenode:
        image: uhopper/hadoop-namenode:2.7.2
        hostname: hdfsnamenode
        volumes:
            - hdfsname:/hadoop/dfs/name
        ports:
            - "50070:50070"  # webui
            - "8020:8020"  # filesystem
        environment:
            - CLUSTER_NAME=ucsp
        deploy:
            placement:
                constraints:
                    - node.hostname == aldorithm

    hdfsdatanode:
        image: uhopper/hadoop-datanode:2.7.2
        hostname: "hdfsdatanode-{{.Node.ID}}"
        depends_on:
            - hdfsnamenode
        volumes:
            - hdfsdatanode:/hadoop/dfs/data
        environment:
            - CORE_CONF_fs_defaultFS=hdfs://hdfsnamenode:8020
        deploy:
            mode: global
            endpoint_mode: dnsrr
            placement:
                constraints:
                    - node.hostname != aldorithm

    yarnresourcemanager:
        image: uhopper/hadoop-resourcemanager:2.7.2
        hostname: yarnresourcemanager
        depends_on:
            - hdfsnamenode
        ports:
            - "8088:8088"  # webui
        environment:
            - CORE_CONF_fs_defaultFS=hdfs://hdfsnamenode:8020
        deploy:
            placement:
                constraints:
                    - node.hostname == aldorithm

    yarnnodemanager:
        image: uhopper/hadoop-nodemanager:2.7.2
        hostname: "yarnnodemanager-{{.Node.ID}}"
        depends_on:
            - hdfsnamenode
            - yarnresourcemanager
        environment:
            - CORE_CONF_fs_defaultFS=hdfs://hdfsnamenode:8020
            - YARN_CONF_yarn_resourcemanager_hostname=yarnresourcemanager
        deploy:
            endpoint_mode: dnsrr
            mode: global
            placement:
                constraints:
                    - node.hostname != aldorithm

    runner:
        image: alculquicondor/hadoop-runner
        build:
            dockerfile: dockerfiles/runner.Dockerfile
            context: .
        volumes:
            - ./data:/root/data
        depends_on:
            - hdfsnamenode
            - yarnresourcemanager
        environment:
            - CORE_CONF_fs_defaultFS=hdfs://hdfsnamenode:8020
            - YARN_CONF_yarn_resourcemanager_hostname=yarnresourcemanager
        command: tail -f /var/log/dmesg
        deploy:
            placement:
                constraints:
                    - node.hostname == aldorithm


volumes:
    hdfsname:
    hdfsdatanode:
